import { supabase } from "@/integrations/supabase/client";

interface OrderItem {
  product_id: string;
  product_name: string;
  product_image: string;
  product_price: number;
  size: string;
  quantity: number;
}

interface ShippingInfo {
  fullName: string;
  email: string;
  phone: string;
  address: string;
  city: string;
  province: string;
  postalCode: string;
  country: string;
}

interface CreateOrderParams {
  items: OrderItem[];
  shippingInfo: ShippingInfo;
  paymentMethod: "cod" | "bank_transfer";
  userId?: string;
}

export async function createOrder({
  items,
  shippingInfo,
  paymentMethod,
  userId,
}: CreateOrderParams): Promise<string> {
  // Check rate limit - use user_id if authenticated, otherwise use email as identifier
  const identifier = userId || shippingInfo.email;
  
  const { data: rateLimitOk, error: rateLimitError } = await supabase
    .rpc('check_order_rate_limit', { user_identifier: identifier });

  if (rateLimitError) {
    throw new Error("Failed to verify rate limit. Please try again.");
  }

  if (!rateLimitOk) {
    throw new Error("Too many orders. Please wait before placing another order (max 5 orders per hour).");
  }

  // Validate payment method
  const allowedMethods = ["cod", "bank_transfer"] as const;
  if (!allowedMethods.includes(paymentMethod)) {
    throw new Error("Invalid payment method. Only 'cod' or 'bank_transfer' are allowed.");
  }

  // Validate stock availability and prices
  for (const item of items) {
    const { data: product, error } = await supabase
      .from("products")
      .select("sizes, price")
      .eq("id", item.product_id)
      .single();

    if (error || !product) throw new Error("Invalid product");

    // Verify price matches database to prevent manipulation
    if (item.product_price !== Number(product.price)) {
      throw new Error(`Price mismatch detected for ${item.product_name}`);
    }

    const sizes = product.sizes as Record<string, number>;
    const availableStock = sizes[item.size] || 0;

    if (availableStock < item.quantity) {
      throw new Error(`Insufficient stock for ${item.product_name} (Size ${item.size})`);
    }
  }

  const subtotal = items.reduce((sum, item) => sum + item.product_price * item.quantity, 0);

  // Create order
  const { data: order, error: orderError } = await supabase
    .from("orders")
    .insert({
      user_id: userId || null,
      customer_name: shippingInfo.fullName,
      customer_email: shippingInfo.email,
      customer_phone: shippingInfo.phone,
      shipping_address: {
        address: shippingInfo.address,
        city: shippingInfo.city,
        province: shippingInfo.province,
        postalCode: shippingInfo.postalCode,
        country: shippingInfo.country,
      },
      payment_method: paymentMethod,
      subtotal,
      total: subtotal,
      order_status: "pending",
      payment_status: "pending",
      order_number: "", // Will be generated by trigger
    })
    .select()
    .single();

  if (orderError) throw orderError;

  // Create order items and update stock
  for (const item of items) {
    const { error: itemError } = await supabase.from("order_items").insert({
      order_id: order.id,
      product_id: item.product_id,
      product_name: item.product_name,
      product_image: item.product_image,
      size: item.size,
      quantity: item.quantity,
      price: item.product_price,
      subtotal: item.product_price * item.quantity,
    });

    if (itemError) throw itemError;

    // Update product stock
    const { data: product } = await supabase
      .from("products")
      .select("sizes")
      .eq("id", item.product_id)
      .single();

    if (product) {
      const sizes = product.sizes as Record<string, number>;
      sizes[item.size] = (sizes[item.size] || 0) - item.quantity;

      await supabase
        .from("products")
        .update({ sizes })
        .eq("id", item.product_id);
    }
  }

  return order.id;
}
